<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Buena.ai API v2
 *
 * The most powerful LinkedIn automation and lead management API for modern sales teams and developers.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@buena.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createApiKey
     *
     * Create API Key.
     *
     */
    public function testCreateApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createLead
     *
     * Create Lead.
     *
     */
    public function testCreateLead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createVoiceClone
     *
     * Create Voice Clone.
     *
     */
    public function testCreateVoiceClone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteVoiceClone
     *
     * Delete Voice Clone.
     *
     */
    public function testDeleteVoiceClone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateVoicePreview
     *
     * Generate Voice Preview.
     *
     */
    public function testGenerateVoicePreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for healthCheck
     *
     * Health Check.
     *
     */
    public function testHealthCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeys
     *
     * List API Keys.
     *
     */
    public function testListApiKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLeads
     *
     * List Leads.
     *
     */
    public function testListLeads()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listVoiceClones
     *
     * List Voice Clones.
     *
     */
    public function testListVoiceClones()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateVoiceClone
     *
     * Update Voice Clone.
     *
     */
    public function testUpdateVoiceClone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
