/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
)

// checks if the ListLeads200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLeads200Response{}

// ListLeads200Response struct for ListLeads200Response
type ListLeads200Response struct {
	Leads []Lead `json:"leads,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewListLeads200Response instantiates a new ListLeads200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLeads200Response() *ListLeads200Response {
	this := ListLeads200Response{}
	return &this
}

// NewListLeads200ResponseWithDefaults instantiates a new ListLeads200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLeads200ResponseWithDefaults() *ListLeads200Response {
	this := ListLeads200Response{}
	return &this
}

// GetLeads returns the Leads field value if set, zero value otherwise.
func (o *ListLeads200Response) GetLeads() []Lead {
	if o == nil || IsNil(o.Leads) {
		var ret []Lead
		return ret
	}
	return o.Leads
}

// GetLeadsOk returns a tuple with the Leads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLeads200Response) GetLeadsOk() ([]Lead, bool) {
	if o == nil || IsNil(o.Leads) {
		return nil, false
	}
	return o.Leads, true
}

// HasLeads returns a boolean if a field has been set.
func (o *ListLeads200Response) HasLeads() bool {
	if o != nil && !IsNil(o.Leads) {
		return true
	}

	return false
}

// SetLeads gets a reference to the given []Lead and assigns it to the Leads field.
func (o *ListLeads200Response) SetLeads(v []Lead) {
	o.Leads = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListLeads200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLeads200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListLeads200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListLeads200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o ListLeads200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLeads200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Leads) {
		toSerialize["leads"] = o.Leads
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableListLeads200Response struct {
	value *ListLeads200Response
	isSet bool
}

func (v NullableListLeads200Response) Get() *ListLeads200Response {
	return v.value
}

func (v *NullableListLeads200Response) Set(val *ListLeads200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLeads200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLeads200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLeads200Response(val *ListLeads200Response) *NullableListLeads200Response {
	return &NullableListLeads200Response{value: val, isSet: true}
}

func (v NullableListLeads200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLeads200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


