/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
)

// checks if the VoiceCloneListResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceCloneListResponseData{}

// VoiceCloneListResponseData struct for VoiceCloneListResponseData
type VoiceCloneListResponseData struct {
	VoiceClones []VoiceClone `json:"voiceClones,omitempty"`
	// Total number of voice clones for the user
	Total *int32 `json:"total,omitempty"`
}

// NewVoiceCloneListResponseData instantiates a new VoiceCloneListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceCloneListResponseData() *VoiceCloneListResponseData {
	this := VoiceCloneListResponseData{}
	return &this
}

// NewVoiceCloneListResponseDataWithDefaults instantiates a new VoiceCloneListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceCloneListResponseDataWithDefaults() *VoiceCloneListResponseData {
	this := VoiceCloneListResponseData{}
	return &this
}

// GetVoiceClones returns the VoiceClones field value if set, zero value otherwise.
func (o *VoiceCloneListResponseData) GetVoiceClones() []VoiceClone {
	if o == nil || IsNil(o.VoiceClones) {
		var ret []VoiceClone
		return ret
	}
	return o.VoiceClones
}

// GetVoiceClonesOk returns a tuple with the VoiceClones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceCloneListResponseData) GetVoiceClonesOk() ([]VoiceClone, bool) {
	if o == nil || IsNil(o.VoiceClones) {
		return nil, false
	}
	return o.VoiceClones, true
}

// HasVoiceClones returns a boolean if a field has been set.
func (o *VoiceCloneListResponseData) HasVoiceClones() bool {
	if o != nil && !IsNil(o.VoiceClones) {
		return true
	}

	return false
}

// SetVoiceClones gets a reference to the given []VoiceClone and assigns it to the VoiceClones field.
func (o *VoiceCloneListResponseData) SetVoiceClones(v []VoiceClone) {
	o.VoiceClones = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VoiceCloneListResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceCloneListResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VoiceCloneListResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *VoiceCloneListResponseData) SetTotal(v int32) {
	o.Total = &v
}

func (o VoiceCloneListResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceCloneListResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VoiceClones) {
		toSerialize["voiceClones"] = o.VoiceClones
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableVoiceCloneListResponseData struct {
	value *VoiceCloneListResponseData
	isSet bool
}

func (v NullableVoiceCloneListResponseData) Get() *VoiceCloneListResponseData {
	return v.value
}

func (v *NullableVoiceCloneListResponseData) Set(val *VoiceCloneListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceCloneListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceCloneListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceCloneListResponseData(val *VoiceCloneListResponseData) *NullableVoiceCloneListResponseData {
	return &NullableVoiceCloneListResponseData{value: val, isSet: true}
}

func (v NullableVoiceCloneListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceCloneListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


