/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateLeadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLeadRequest{}

// CreateLeadRequest struct for CreateLeadRequest
type CreateLeadRequest struct {
	// First name of the lead
	FirstName string `json:"first_name"`
	// Last name of the lead
	LastName string `json:"last_name"`
	// Email address of the lead
	Email *string `json:"email,omitempty"`
	// Company name
	Company *string `json:"company,omitempty"`
	// Job title
	Title *string `json:"title,omitempty"`
	// LinkedIn profile URL
	LinkedinUrl *string `json:"linkedin_url,omitempty"`
}

type _CreateLeadRequest CreateLeadRequest

// NewCreateLeadRequest instantiates a new CreateLeadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLeadRequest(firstName string, lastName string) *CreateLeadRequest {
	this := CreateLeadRequest{}
	this.FirstName = firstName
	this.LastName = lastName
	return &this
}

// NewCreateLeadRequestWithDefaults instantiates a new CreateLeadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLeadRequestWithDefaults() *CreateLeadRequest {
	this := CreateLeadRequest{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *CreateLeadRequest) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *CreateLeadRequest) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *CreateLeadRequest) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *CreateLeadRequest) SetLastName(v string) {
	o.LastName = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateLeadRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateLeadRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateLeadRequest) SetEmail(v string) {
	o.Email = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *CreateLeadRequest) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *CreateLeadRequest) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *CreateLeadRequest) SetCompany(v string) {
	o.Company = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateLeadRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateLeadRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateLeadRequest) SetTitle(v string) {
	o.Title = &v
}

// GetLinkedinUrl returns the LinkedinUrl field value if set, zero value otherwise.
func (o *CreateLeadRequest) GetLinkedinUrl() string {
	if o == nil || IsNil(o.LinkedinUrl) {
		var ret string
		return ret
	}
	return *o.LinkedinUrl
}

// GetLinkedinUrlOk returns a tuple with the LinkedinUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLeadRequest) GetLinkedinUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LinkedinUrl) {
		return nil, false
	}
	return o.LinkedinUrl, true
}

// HasLinkedinUrl returns a boolean if a field has been set.
func (o *CreateLeadRequest) HasLinkedinUrl() bool {
	if o != nil && !IsNil(o.LinkedinUrl) {
		return true
	}

	return false
}

// SetLinkedinUrl gets a reference to the given string and assigns it to the LinkedinUrl field.
func (o *CreateLeadRequest) SetLinkedinUrl(v string) {
	o.LinkedinUrl = &v
}

func (o CreateLeadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLeadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.LinkedinUrl) {
		toSerialize["linkedin_url"] = o.LinkedinUrl
	}
	return toSerialize, nil
}

func (o *CreateLeadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"last_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLeadRequest := _CreateLeadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLeadRequest)

	if err != nil {
		return err
	}

	*o = CreateLeadRequest(varCreateLeadRequest)

	return err
}

type NullableCreateLeadRequest struct {
	value *CreateLeadRequest
	isSet bool
}

func (v NullableCreateLeadRequest) Get() *CreateLeadRequest {
	return v.value
}

func (v *NullableCreateLeadRequest) Set(val *CreateLeadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLeadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLeadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLeadRequest(val *CreateLeadRequest) *NullableCreateLeadRequest {
	return &NullableCreateLeadRequest{value: val, isSet: true}
}

func (v NullableCreateLeadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLeadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


