/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
	"time"
)

// checks if the UpdateVoiceCloneResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVoiceCloneResponseData{}

// UpdateVoiceCloneResponseData struct for UpdateVoiceCloneResponseData
type UpdateVoiceCloneResponseData struct {
	// Updated name for the voice clone
	Name *string `json:"name,omitempty"`
	// Updated description of the voice clone
	Description *string `json:"description,omitempty"`
	// Updated active status
	IsActive *bool `json:"isActive,omitempty"`
	// When the voice clone was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewUpdateVoiceCloneResponseData instantiates a new UpdateVoiceCloneResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVoiceCloneResponseData() *UpdateVoiceCloneResponseData {
	this := UpdateVoiceCloneResponseData{}
	return &this
}

// NewUpdateVoiceCloneResponseDataWithDefaults instantiates a new UpdateVoiceCloneResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVoiceCloneResponseDataWithDefaults() *UpdateVoiceCloneResponseData {
	this := UpdateVoiceCloneResponseData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateVoiceCloneResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVoiceCloneResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateVoiceCloneResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateVoiceCloneResponseData) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateVoiceCloneResponseData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVoiceCloneResponseData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateVoiceCloneResponseData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateVoiceCloneResponseData) SetDescription(v string) {
	o.Description = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *UpdateVoiceCloneResponseData) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVoiceCloneResponseData) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *UpdateVoiceCloneResponseData) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *UpdateVoiceCloneResponseData) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UpdateVoiceCloneResponseData) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVoiceCloneResponseData) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UpdateVoiceCloneResponseData) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UpdateVoiceCloneResponseData) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o UpdateVoiceCloneResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVoiceCloneResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableUpdateVoiceCloneResponseData struct {
	value *UpdateVoiceCloneResponseData
	isSet bool
}

func (v NullableUpdateVoiceCloneResponseData) Get() *UpdateVoiceCloneResponseData {
	return v.value
}

func (v *NullableUpdateVoiceCloneResponseData) Set(val *UpdateVoiceCloneResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVoiceCloneResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVoiceCloneResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVoiceCloneResponseData(val *UpdateVoiceCloneResponseData) *NullableUpdateVoiceCloneResponseData {
	return &NullableUpdateVoiceCloneResponseData{value: val, isSet: true}
}

func (v NullableUpdateVoiceCloneResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVoiceCloneResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


