/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoicePreviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoicePreviewRequest{}

// VoicePreviewRequest struct for VoicePreviewRequest
type VoicePreviewRequest struct {
	// The ID of the voice clone to use for preview generation
	VoiceId string `json:"voiceId"`
	// Text to synthesize into speech (1-500 characters)
	Text string `json:"text"`
}

type _VoicePreviewRequest VoicePreviewRequest

// NewVoicePreviewRequest instantiates a new VoicePreviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoicePreviewRequest(voiceId string, text string) *VoicePreviewRequest {
	this := VoicePreviewRequest{}
	this.VoiceId = voiceId
	this.Text = text
	return &this
}

// NewVoicePreviewRequestWithDefaults instantiates a new VoicePreviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoicePreviewRequestWithDefaults() *VoicePreviewRequest {
	this := VoicePreviewRequest{}
	return &this
}

// GetVoiceId returns the VoiceId field value
func (o *VoicePreviewRequest) GetVoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VoiceId
}

// GetVoiceIdOk returns a tuple with the VoiceId field value
// and a boolean to check if the value has been set.
func (o *VoicePreviewRequest) GetVoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VoiceId, true
}

// SetVoiceId sets field value
func (o *VoicePreviewRequest) SetVoiceId(v string) {
	o.VoiceId = v
}

// GetText returns the Text field value
func (o *VoicePreviewRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *VoicePreviewRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *VoicePreviewRequest) SetText(v string) {
	o.Text = v
}

func (o VoicePreviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoicePreviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["voiceId"] = o.VoiceId
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *VoicePreviewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"voiceId",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoicePreviewRequest := _VoicePreviewRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoicePreviewRequest)

	if err != nil {
		return err
	}

	*o = VoicePreviewRequest(varVoicePreviewRequest)

	return err
}

type NullableVoicePreviewRequest struct {
	value *VoicePreviewRequest
	isSet bool
}

func (v NullableVoicePreviewRequest) Get() *VoicePreviewRequest {
	return v.value
}

func (v *NullableVoicePreviewRequest) Set(val *VoicePreviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVoicePreviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVoicePreviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoicePreviewRequest(val *VoicePreviewRequest) *NullableVoicePreviewRequest {
	return &NullableVoicePreviewRequest{value: val, isSet: true}
}

func (v NullableVoicePreviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoicePreviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


