/*
Buena.ai API v2

The most powerful LinkedIn automation and lead management API for modern sales teams and developers.

API version: 2.0.0
Contact: support@buena.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buena

import (
	"encoding/json"
)

// checks if the VoiceCloneListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceCloneListResponse{}

// VoiceCloneListResponse struct for VoiceCloneListResponse
type VoiceCloneListResponse struct {
	Success *bool `json:"success,omitempty"`
	Data *VoiceCloneListResponseData `json:"data,omitempty"`
}

// NewVoiceCloneListResponse instantiates a new VoiceCloneListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceCloneListResponse() *VoiceCloneListResponse {
	this := VoiceCloneListResponse{}
	return &this
}

// NewVoiceCloneListResponseWithDefaults instantiates a new VoiceCloneListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceCloneListResponseWithDefaults() *VoiceCloneListResponse {
	this := VoiceCloneListResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VoiceCloneListResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceCloneListResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VoiceCloneListResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VoiceCloneListResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VoiceCloneListResponse) GetData() VoiceCloneListResponseData {
	if o == nil || IsNil(o.Data) {
		var ret VoiceCloneListResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceCloneListResponse) GetDataOk() (*VoiceCloneListResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VoiceCloneListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given VoiceCloneListResponseData and assigns it to the Data field.
func (o *VoiceCloneListResponse) SetData(v VoiceCloneListResponseData) {
	o.Data = &v
}

func (o VoiceCloneListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceCloneListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableVoiceCloneListResponse struct {
	value *VoiceCloneListResponse
	isSet bool
}

func (v NullableVoiceCloneListResponse) Get() *VoiceCloneListResponse {
	return v.value
}

func (v *NullableVoiceCloneListResponse) Set(val *VoiceCloneListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceCloneListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceCloneListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceCloneListResponse(val *VoiceCloneListResponse) *NullableVoiceCloneListResponse {
	return &NullableVoiceCloneListResponse{value: val, isSet: true}
}

func (v NullableVoiceCloneListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceCloneListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


