name: 🟡 Auto-Update TypeScript SDK

on:
  push:
    paths:
      - "typescript/**"
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        working-directory: ./typescript
        run: npm ci

      - name: Build
        working-directory: ./typescript
        run: npm run build

      - name: Run tests
        working-directory: ./typescript
        run: npm test || echo "No tests defined"

      - name: Auto-bump version
        working-directory: ./typescript
        run: |
          # Get current version and increment patch
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Publish to npm
        working-directory: ./typescript
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add typescript/package.json typescript/package-lock.json
          git commit -m "🤖 Auto-bump TypeScript SDK version" || exit 0
          git push
