name: 📦 Publish TypeScript SDK to npm

on:
  push:
    paths:
      - "typescript/package.json"
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ./typescript
        run: npm install

      - name: Build SDK
        working-directory: ./typescript
        run: npm run build

      - name: Publish to npm
        working-directory: ./typescript
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
