name: 🟣 Update Packagist

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: curl, json, mbstring

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Update Packagist
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/Buena-AI/buena-php-sdk"}}' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"
